import { defineConfig, type DummyRuleMap } from 'oxlint';
import commonConfig from '../.oxlintrc.json' with { type: 'json' };

function config() {
  return defineConfig({
    // @ts-expect-error JSON files cannot be imported as `const`...
    extends: [commonConfig],
    plugins: [
      'eslint',
      'import',
      'jsx-a11y',
      'oxc',
      'promise',
      'react',
      'typescript',
      'unicorn',
    ],
    jsPlugins: [
      'eslint-plugin-lingui',
      'eslint-plugin-react-x',
      'eslint-plugin-react-jsx',
      'eslint-plugin-react-dom',
      'eslint-plugin-react-web-api',
      'eslint-plugin-react-hooks-extra',
      'eslint-plugin-react-naming-convention',
    ],
    env: {
      builtin: true,
    },
    ignorePatterns: [
      'node_modules',
      'shared',
      'assets',
      'build',
      '.vite',
      '__mocks__',
      'panda.config.ts',
      'vite.config.*',
      '.storybook/vite.config.*',
      'src/graphql/generated.d.ts',
      'src/locales/',
      'src/styled-system/generated/',
      'src/styled-system/tokens/',
    ],
    rules: {
      ...coreRules,
      ...oxcRules,
      ...importRules,
      ...jsxA11yRules,
      ...linguiRules,
      ...promiseRules,
      ...reactRules,
      ...unicornRules,
    },
  });
}

const coreRules: DummyRuleMap = {
  'constructor-super': 'error',
  'func-style': ['error', 'declaration'],
  'for-direction': 'error',
  'getter-return': 'error',
  'no-array-constructor': 'error',
  'no-async-promise-executor': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-const-assign': 'error',
  'no-constant-binary-expression': 'error',
  'no-constant-condition': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty-character-class': 'error',
  'no-empty-pattern': 'error',
  'no-empty-static-block': 'error',
  'no-empty': 'error',
  'no-ex-assign': 'error',
  'no-extra-boolean-cast': 'error',
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-import-assign': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-loss-of-precision': 'error',
  'no-misleading-character-class': 'error',
  'no-new-native-nonconstructor': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-obj-calls': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-self-assign': 'error',
  'no-setter-return': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-this-before-super': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-expressions': 'error',
  'no-unused-labels': 'error',
  'no-unused-private-class-members': 'error',
  'no-unused-vars': [
    'error',
    {
      argsIgnorePattern: '^_',
      caughtErrorsIgnorePattern: '^_',
      destructuredArrayIgnorePattern: '^_',
    },
  ],
  'no-useless-backreference': 'error',
  'no-useless-catch': 'error',
  'no-useless-escape': 'error',
  'no-with': 'error',
  'no-use-before-define': 'off',
  'require-yield': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',
  'accessor-pairs': 'error',
  'array-callback-return': 'error',
  eqeqeq: 'error',
  'no-alert': 'error',
  'no-constructor-return': 'error',
  'no-empty-function': 'error',
  'no-eq-null': 'error',
  'no-extra-bind': 'error',
  'no-loop-func': 'error',
  'no-new': 'error',
  'no-new-wrappers': 'error',
  'no-object-constructor': 'error',
  'no-param-reassign': 'error',
  'no-promise-executor-return': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-shadow': 'error',
  'no-throw-literal': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'prefer-const': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  radix: 'error',
  'require-await': 'error',
};

const oxcRules: DummyRuleMap = {
  'oxc/bad-array-method-on-arguments': 'error',
  'oxc/bad-char-at-comparison': 'error',
  'oxc/bad-comparison-sequence': 'error',
  'oxc/bad-min-max-func': 'error',
  'oxc/bad-object-literal-comparison': 'error',
  'oxc/bad-replace-all-arg': 'error',
  'oxc/const-comparisons': 'error',
  'oxc/double-comparisons': 'error',
  'oxc/erasing-op': 'error',
  'oxc/missing-throw': 'error',
  'oxc/number-arg-out-of-range': 'error',
  'oxc/only-used-in-recursion': 'error',
  'oxc/uninvoked-array-callback': 'error',
};

const jsxA11yRules: DummyRuleMap = {
  'jsx-a11y/alt-text': 'error',
  'jsx-a11y/anchor-has-content': 'error',
  'jsx-a11y/anchor-is-valid': 'error',
  'jsx-a11y/aria-activedescendant-has-tabindex': 'error',
  'jsx-a11y/aria-props': 'error',
  'jsx-a11y/aria-proptypes': 'error',
  'jsx-a11y/aria-role': 'error',
  'jsx-a11y/aria-unsupported-elements': 'error',
  'jsx-a11y/autocomplete-valid': 'error',
  'jsx-a11y/click-events-have-key-events': 'error',
  'jsx-a11y/heading-has-content': 'error',
  'jsx-a11y/html-has-lang': 'error',
  'jsx-a11y/iframe-has-title': 'error',
  'jsx-a11y/img-redundant-alt': 'error',
  'jsx-a11y/interactive-supports-focus': [
    'error',
    {
      tabbable: [
        'button',
        'checkbox',
        'link',
        'searchbox',
        'spinbutton',
        'switch',
        'textbox',
      ],
    },
  ],
  'jsx-a11y/label-has-associated-control': 'error',
  'jsx-a11y/media-has-caption': 'error',
  'jsx-a11y/mouse-events-have-key-events': 'error',
  'jsx-a11y/no-access-key': 'error',
  'jsx-a11y/no-autofocus': 'error',
  'jsx-a11y/no-distracting-elements': 'error',
  'jsx-a11y/no-interactive-element-to-noninteractive-role': [
    'error',
    {
      tr: ['none', 'presentation'],
      canvas: ['img'],
    },
  ],
  'jsx-a11y/no-noninteractive-element-interactions': [
    'error',
    {
      handlers: [
        'onClick',
        'onError',
        'onLoad',
        'onMouseDown',
        'onMouseUp',
        'onKeyPress',
        'onKeyDown',
        'onKeyUp',
      ],
      alert: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
      body: ['onError', 'onLoad'],
      dialog: ['onKeyUp', 'onKeyDown', 'onKeyPress'],
      iframe: ['onError', 'onLoad'],
      img: ['onError', 'onLoad'],
    },
  ],
  'jsx-a11y/no-noninteractive-element-to-interactive-role': [
    'error',
    {
      ul: [
        'listbox',
        'menu',
        'menubar',
        'radiogroup',
        'tablist',
        'tree',
        'treegrid',
      ],
      ol: [
        'listbox',
        'menu',
        'menubar',
        'radiogroup',
        'tablist',
        'tree',
        'treegrid',
      ],
      li: [
        'menuitem',
        'menuitemradio',
        'menuitemcheckbox',
        'option',
        'row',
        'tab',
        'treeitem',
      ],
      table: ['grid'],
      td: ['gridcell'],
      fieldset: ['radiogroup', 'presentation'],
    },
  ],
  'jsx-a11y/no-noninteractive-tabindex': [
    'error',
    {
      tags: [],
      roles: ['tabpanel'],
      allowExpressionValues: true,
    },
  ],
  'jsx-a11y/no-redundant-roles': 'error',
  'jsx-a11y/no-static-element-interactions': [
    'error',
    {
      allowExpressionValues: true,
      handlers: [
        'onClick',
        'onMouseDown',
        'onMouseUp',
        'onKeyPress',
        'onKeyDown',
        'onKeyUp',
      ],
    },
  ],
  'jsx-a11y/role-has-required-aria-props': 'error',
  'jsx-a11y/role-supports-aria-props': 'error',
  'jsx-a11y/scope': 'error',
  'jsx-a11y/tabindex-no-positive': 'error',
};

const linguiRules: DummyRuleMap = {
  'lingui/t-call-in-function': 'error',
  'lingui/no-single-tag-to-translate': 'error',
  'lingui/no-single-variables-to-translate': 'error',
  'lingui/no-trans-inside-trans': 'error',
  'lingui/no-expression-in-message': 'error',
};

const importRules: DummyRuleMap = {
  'import/namespace': 'error',
  'import/default': 'error',
  'import/no-named-as-default': 'error',
  'import/no-named-as-default-member': 'error',
  'import/no-duplicates': 'error',
  'no-restricted-imports': [
    'error',
    {
      name: '@tanstack/react-router',
      importNames: ['Link'],
      message: 'Please use custom Link instead.',
    },
    {
      name: 'react-aria-components',
      importNames: ['Link'],
      message: 'Please use custom Link instead.',
    },
    {
      name: '~/styled-system/jsx',
      importNames: ['Stack'],
      message: 'Please use custom Stack from uikit instead.',
    },
    {
      name: 'sonner',
      importNames: ['toast', 'Toaster'],
      message:
        'Please use the custom toast function from uikit/toaster instead.',
    },
    {
      name: '@lingui/react',
      importNames: ['Trans', 'useLingui'],
      message: 'Please use the @lingui/react/macro instead.',
    },
    {
      name: '@apollo/client/react',
      importNames: ['useQuery', 'useSuspenseQuery', 'useReadQuery', 'gql'],
      message:
        'Please use GraphQL related hooks and utils from ~/graphql alias.',
    },
    {
      name: 'gql.tada',
      importNames: ['graphql'],
      message:
        'Please use GraphQL related hooks and utils from ~/graphql alias.',
    },
    {
      name: 'graphql',
      importNames: ['graphql'],
      message:
        'Please use GraphQL related hooks and utils from ~/graphql alias.',
    },
  ],
};

const promiseRules: DummyRuleMap = {
  'promise/always-return': 'error',
  'promise/no-return-wrap': 'error',
  'promise/param-names': 'error',
  'promise/catch-or-return': 'error',
  'promise/no-nesting': 'error',
  'promise/no-promise-in-callback': 'error',
  'promise/no-callback-in-promise': 'error',
  'promise/no-new-statics': 'error',
  'promise/valid-params': 'error',
};

const reactRules: DummyRuleMap = {
  'react/exhaustive-deps': 'off',
  'react/react-compiler': 'error',
  'react/rules-of-hooks': 'error',
  'react-jsx/no-children-prop': 'error',
  'react-jsx/no-children-prop-with-children': 'error',
  'react-jsx/no-comment-textnodes': 'error',
  'react-jsx/no-key-after-spread': 'error',
  'react-jsx/no-leaked-dollar': 'error',
  'react-jsx/no-leaked-semicolon': 'error',
  'react-jsx/no-namespace': 'error',
  'react-jsx/no-useless-fragment': 'error',
  'react-x/no-access-state-in-setstate': 'error',
  'react-x/no-array-index-key': 'error',
  'react-x/no-children-count': 'off',
  'react-x/no-children-for-each': 'error',
  'react-x/no-children-map': 'off',
  'react-x/no-children-only': 'error',
  'react-x/no-children-to-array': 'error',
  'react-x/no-clone-element': 'off',
  'react-x/no-component-will-mount': 'error',
  'react-x/no-component-will-receive-props': 'error',
  'react-x/no-component-will-update': 'error',
  'react-x/no-context-provider': 'error',
  'react-x/no-create-ref': 'error',
  'react-x/no-direct-mutation-state': 'error',
  'react-x/no-duplicate-key': 'error',
  'react-x/no-forward-ref': 'error',
  'react-x/no-missing-key': 'error',
  'react-x/no-misused-capture-owner-stack': 'error',
  'react-x/no-nested-component-definitions': 'error',
  'react-x/no-nested-lazy-component-declarations': 'error',
  'react-x/no-unstable-context-value': 'off',
  'react-x/no-unstable-default-props': 'error',
  'react-x/no-unused-state': 'error',
  'react-x/no-use-context': 'error',
  'react-x/no-unnecessary-use-prefix': 'error',
  'react-dom/no-dangerously-set-innerhtml': 'error',
  'react-dom/no-dangerously-set-innerhtml-with-children': 'error',
  'react-dom/no-find-dom-node': 'error',
  'react-dom/no-flush-sync': 'error',
  'react-dom/no-hydrate': 'error',
  'react-dom/no-missing-button-type': 'error',
  'react-dom/no-missing-iframe-sandbox': 'error',
  'react-dom/no-render': 'error',
  'react-dom/no-render-return-value': 'error',
  'react-dom/no-script-url': 'error',
  'react-dom/no-unsafe-iframe-sandbox': 'error',
  'react-dom/no-unsafe-target-blank': 'error',
  'react-dom/no-use-form-state': 'error',
  'react-dom/no-void-elements-with-children': 'error',
  'react-web-api/no-leaked-event-listener': 'error',
  'react-web-api/no-leaked-interval': 'error',
  'react-web-api/no-leaked-resize-observer': 'error',
  'react-web-api/no-leaked-timeout': 'error',
  'react-hooks-extra/no-direct-set-state-in-use-effect': 'error',
  'react-naming-convention/context-name': 'error',
  'react-dom/no-unknown-property': 'off',
};

const unicornRules: DummyRuleMap = {
  'unicorn/no-await-in-promise-methods': 'error',
  'unicorn/no-empty-file': 'error',
  'unicorn/no-invalid-fetch-options': 'error',
  'unicorn/no-invalid-remove-event-listener': 'error',
  'unicorn/no-new-array': 'error',
  'unicorn/no-single-promise-in-promise-methods': 'error',
  'unicorn/no-thenable': 'error',
  'unicorn/no-unnecessary-await': 'error',
  'unicorn/no-useless-fallback-in-spread': 'error',
  'unicorn/no-useless-length-check': 'error',
  'unicorn/no-useless-spread': 'error',
  'unicorn/prefer-set-size': 'error',
  'unicorn/prefer-string-starts-ends-with': 'error',
};

export default config();
