{{- $root := . -}}
{{- $defaults := .Values.serviceDefaults -}}

{{- range $serviceName, $serviceEnabled := .Values.services }}
{{- if $serviceEnabled }}
{{- with (index $root.Values $serviceName) }}
{{- if not .type }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" $root }}-{{ $serviceName }}
  labels:
    app: {{ template "name" $root }}
    chart: {{ $root.Chart.Name }}-{{ $root.Chart.Version | replace "+" "_" }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  selector:
    app: {{ template "name" $root }}
    release: {{ $root.Release.Name }}
    tier: {{ .tier | default $defaults.tier }}
    role: {{ $serviceName }}
  ports:
    - name: service
      port: {{ .port | default $defaults.port }}
    {{- if .sidecar }}
    {{- if .sidecar.enabled }}
    {{- if .sidecar.port }}
    - name: sidecar
      port: {{ .sidecar.port}}
    {{- end }}
    {{- end }}
    {{- end }}

---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
