query readPosts {
  posts {
    total
    data {
      id
      subject
      content
      author
    }
  }
}

mutation createPost($subject: String!, $content: String!, $author: String!) {
  createPost(input: { subject: $subject, content: $content, author: $author }) {
    id
    subject
    content
    author
  }
}
