/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root';
import { Route as layoutRouteImport } from './routes/layout';
import { Route as loginLoginDotrouteRouteImport } from './routes/login/login.route';
import { Route as homeHomeDotrouteRouteImport } from './routes/home/home.route';
import { Route as notFoundNotFoundDotrouteRouteImport } from './routes/not-found/not-found.route';

const layoutRoute = layoutRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any);
const loginLoginDotrouteRoute = loginLoginDotrouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const homeHomeDotrouteRoute = homeHomeDotrouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutRoute,
} as any);
const notFoundNotFoundDotrouteRoute =
  notFoundNotFoundDotrouteRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => layoutRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/login': typeof loginLoginDotrouteRoute;
  '/': typeof homeHomeDotrouteRoute;
  '/$': typeof notFoundNotFoundDotrouteRoute;
}
export interface FileRoutesByTo {
  '/login': typeof loginLoginDotrouteRoute;
  '/': typeof homeHomeDotrouteRoute;
  '/$': typeof notFoundNotFoundDotrouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/login': typeof loginLoginDotrouteRoute;
  '/_app': typeof layoutRouteWithChildren;
  '/_app/': typeof homeHomeDotrouteRoute;
  '/_app/$': typeof notFoundNotFoundDotrouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/login' | '/' | '/$';
  fileRoutesByTo: FileRoutesByTo;
  to: '/login' | '/' | '/$';
  id: '__root__' | '/login' | '/_app' | '/_app/' | '/_app/$';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  loginLoginDotrouteRoute: typeof loginLoginDotrouteRoute;
  layoutRoute: typeof layoutRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof layoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof loginLoginDotrouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_app/': {
      id: '/_app/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof homeHomeDotrouteRouteImport;
      parentRoute: typeof layoutRoute;
    };
    '/_app/$': {
      id: '/_app/$';
      path: '/$';
      fullPath: '/$';
      preLoaderRoute: typeof notFoundNotFoundDotrouteRouteImport;
      parentRoute: typeof layoutRoute;
    };
  }
}

interface layoutRouteChildren {
  homeHomeDotrouteRoute: typeof homeHomeDotrouteRoute;
  notFoundNotFoundDotrouteRoute: typeof notFoundNotFoundDotrouteRoute;
}

const layoutRouteChildren: layoutRouteChildren = {
  homeHomeDotrouteRoute: homeHomeDotrouteRoute,
  notFoundNotFoundDotrouteRoute: notFoundNotFoundDotrouteRoute,
};

const layoutRouteWithChildren =
  layoutRoute._addFileChildren(layoutRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  loginLoginDotrouteRoute: loginLoginDotrouteRoute,
  layoutRoute: layoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
