image:
  name: $template_default_taito_image
  username: $template_default_taito_image_username
  password: $template_default_taito_image_password
  email: $template_default_taito_image_email
options:
  docker: true
  max-time: 60

pipelines:
  branches:
    # TODO: support for feature/* (cancel build if not included in taito_environments)
    '{dev,test,stag,canary,master}':
    # Prepare build
    - step:
        script:
          - export taito_mode=ci
          - taito build-prepare:$BITBUCKET_BRANCH
    # Prepare artifacts in parallel
    - parallel:
      - step: # admin
          script:
            - export taito_mode=ci
            - taito artifact-prepare:admin:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # client
          script:
            - export taito_mode=ci
            - taito artifact-prepare:client:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # graphql
          script:
            - export taito_mode=ci
            - taito artifact-prepare:graphql:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # server
          script:
            - export taito_mode=ci
            - taito artifact-prepare:server:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # www
          script:
            - export taito_mode=ci
            - taito artifact-prepare:www:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
    # Deploy the changes to target environment
    - step:
        script:
          - export taito_mode=ci
          - taito db-deploy:$BITBUCKET_BRANCH
    - step:
        script:
          - export taito_mode=ci
          - taito deployment-deploy:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
        # TODO: revert deployment on fail
        # after-script:
        #   - [ $BITBUCKET_EXIT_CODE != 0 ] && taito deployment-revert:$BITBUCKET_BRANCH $BITBUCKET_COMMIT || :
        #   - [ $BITBUCKET_EXIT_CODE != 0 ] && taito db-revert:$BITBUCKET_BRANCH $BITBUCKET_COMMIT || :
    # Test and verify deployment
    - step:
        script:
          - export taito_mode=ci
          - taito deployment-wait:$BITBUCKET_BRANCH
          - taito test:$BITBUCKET_BRANCH
          - taito deployment-verify:$BITBUCKET_BRANCH
        # # TODO: revert deployment on fail
        # after-script:
        #   - [ $BITBUCKET_EXIT_CODE != 0 ] && taito deployment-revert:$BITBUCKET_BRANCH $BITBUCKET_COMMIT || :
        #   - [ $BITBUCKET_EXIT_CODE != 0 ] && taito db-revert:$BITBUCKET_BRANCH $BITBUCKET_COMMIT || :
    # Release artifacts (push previously built container images with a new tag)
    - parallel:
      - step: # admin
          script:
            - export taito_mode=ci
            - taito artifact-release:admin:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # client
          script:
            - export taito_mode=ci
            - taito artifact-release:client:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # graphql
          script:
            - export taito_mode=ci
            - taito artifact-release:graphql:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # server
          script:
            - export taito_mode=ci
            - taito artifact-release:server:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # www
          script:
            - export taito_mode=ci
            - taito artifact-release:www:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
    # Release build
    - step:
        script:
          - export taito_mode=ci
          - taito build-release:$BITBUCKET_BRANCH
