image:
  name: $template_default_taito_image
  username: $template_default_taito_image_username
  password: $template_default_taito_image_password
  email: $template_default_taito_image_email
options:
  docker: true
  max-time: 60

pipelines:
  branches:
    '{dev,test,stag,canary,master}':
    # Install libraries
    - step:
        script:
          - export taito_mode=ci
          - taito install:$BITBUCKET_BRANCH
    - step:
        script:
          - export taito_mode=ci
          - taito artifact-prepare:$BITBUCKET_BRANCH
    - parallel:
      # Execute code scans, documentation generation, and container build/push
      # in parallel
      - step:
          script:
            - export taito_mode=ci
            - taito scan:$BITBUCKET_BRANCH
      - step:
          script:
            - export taito_mode=ci
            - taito docs:$BITBUCKET_BRANCH
      - step: # admin
          script:
            - export taito_mode=ci
            - taito artifact-build:admin:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
            - taito artifact-push:admin:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # client
          script:
            - export taito_mode=ci
            - taito artifact-build:client:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
            - taito artifact-push:client:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # graphql
          script:
            - export taito_mode=ci
            - taito artifact-build:graphql:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
            - taito artifact-push:graphql:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # server
          script:
            - export taito_mode=ci
            - taito artifact-build:server:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
            - taito artifact-push:server:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # www
          script:
            - export taito_mode=ci
            - taito artifact-build:www:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
            - taito artifact-push:www:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
    # Deploy the changes
    - step:
        script:
          - export taito_mode=ci
          - taito db-deploy:$BITBUCKET_BRANCH
    - step:
        script:
          - export taito_mode=ci
          - taito deployment-deploy:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
    # Test and verify deployment
    - step:
        script:
          - export taito_mode=ci
          - taito deployment-wait:$BITBUCKET_BRANCH
          # TODO: tests require docker images from the previous steps!
          # - taito test:$BITBUCKET_BRANCH
          # - taito deployment-verify:$BITBUCKET_BRANCH
    # Publish artifacts and release
    - step:
        script:
          - export taito_mode=ci
          - taito artifact-publish:$BITBUCKET_BRANCH
          - taito artifact-release:$BITBUCKET_BRANCH
    - parallel:
      # Verify images by pushing them with the -untested tag prefix
      - step: # admin
          script:
            - export taito_mode=ci
            - taito artifact-verify:admin:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # client
          script:
            - export taito_mode=ci
            - taito artifact-verify:client:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # graphql
          script:
            - export taito_mode=ci
            - taito artifact-verify:graphql:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # server
          script:
            - export taito_mode=ci
            - taito artifact-verify:server:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
      - step: # www
          script:
            - export taito_mode=ci
            - taito artifact-verify:www:$BITBUCKET_BRANCH $BITBUCKET_COMMIT
