timeout: 3000s

# If you want to grant outsiders access to your build logs, you may save
# the logs to a separate bucket determined by the logsBucket setting and
# grant the outsiders access to the bucket
# logsBucket: 'gs://my-builds' # TODO _TEMPLATE_DEFAULT for this also

substitutions:
  _REPO_NAME: full-stack-template
  _IMAGE_REGISTRY: eu.gcr.io/$PROJECT_ID
  _TAITO_CI_PHASES:
  _VC_TOKEN:

steps:

# NOTE: This first step is an optimization. We execute CI/CD build cancel with
# the google provided gcloud container instead of Taito CLI, because it
# doesn't need to be pulled before execution -> cancel executes immediately.
- id: manual-cancel
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  env:
    - branch_name=$BRANCH_NAME
    - build_id=$BUILD_ID
    - full_repo_name=$_REPO_NAME
  args:
  - '-c'
  - |
    export taito_target_env="$${branch_name//master/prod}"
    source ./taito-config.sh
    echo "- Cancel all previous ongoing builds targetting the same branch"
    gcloud builds list --ongoing | \
      grep "$${full_repo_name}@$${branch_name}" | \
      grep -v "$${build_id}" | \
      cut -d ' ' -f 1 | \
      xargs -L1 gcloud builds cancel 2> /dev/null || :

# ----------------------- Taito CLI ----------------------------------

# Prepare build

- id: build-prepare
  waitFor: ['-']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['build-prepare:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}
    - VC_TOKEN=${_VC_TOKEN}

# Build artifacts in parallel

- id: artifact-prepare-admin
  waitFor: ['build-prepare']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-prepare:admin:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

- id: artifact-prepare-client
  waitFor: ['build-prepare']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-prepare:client:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

- id: artifact-prepare-graphql
  waitFor: ['build-prepare']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-prepare:graphql:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

- id: artifact-prepare-server
  waitFor: ['build-prepare']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-prepare:server:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

- id: artifact-prepare-www
  waitFor: ['build-prepare']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-prepare:www:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

# Deploy to target environment

- id: db-deploy
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['db-deploy:$BRANCH_NAME']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

- id: deployment-deploy
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['deployment-deploy:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

# Test and verify deployment

- id: deployment-wait
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['deployment-wait:$BRANCH_NAME']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

- id: test
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['test:$BRANCH_NAME']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}
    - taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}

- id: deployment-verify
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['deployment-verify:$BRANCH_NAME']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

# Release artifacts in parallel

- id: artifact-release-admin
  waitFor: ['deployment-verify']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-release:admin:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

- id: artifact-release-client
  waitFor: ['deployment-verify']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-release:client:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

- id: artifact-release-graphql
  waitFor: ['deployment-verify']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-release:graphql:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

- id: artifact-release-server
  waitFor: ['deployment-verify']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-release:server:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

- id: artifact-release-www
  waitFor: ['deployment-verify']
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['artifact-release:www:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}

# Release build

- id: build-release
  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
  args: ['build-release:$BRANCH_NAME']
  env:
    - taito_mode=ci
    - taito_ci_phases=${_TAITO_CI_PHASES}
    - VC_TOKEN=${_VC_TOKEN}
