steps:

# NOTE: This first ugly step is an optimization. We execute cancel with
# the google provided kubectl container instead of taito-cli, because it
# doesn't need to be pulled before execution -> cancel executes immediately.
- id: ci-cancel
  name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  env:
    - branch_name=$BRANCH_NAME
    - commit_sha=$COMMIT_SHA
    - build_id=$BUILD_ID
    - full_repo_name=$REPO_NAME
    - image_path=eu.gcr.io/$PROJECT_ID/$REPO_NAME/client:$COMMIT_SHA
  args:
  - '-c'
  - |
    export taito_env
    taito_env="$${branch_name}"
    if [[ "$${taito_env}" == "master" ]]; then
      taito_env="prod"
    fi
    source ./taito-config.sh

    echo "- Get gcloud credentials"
    gcloud container clusters get-credentials "$${kubectl_name}" \
      --zone "$${gcloud_zone}"
    if [[ $$? -gt 0 ]]; then
      exit 1
    fi

    echo "- Cancel all previous ongoing builds targetting the same branch"
    # TODO just in case: filter builds that are newer than this build
    # --> remeber to implement it also in the taito-cli cancel plugin
    gcloud beta container builds list --ongoing | \
      grep "$${full_repo_name}@$${branch_name}" | \
      grep -v "$${build_id}" | \
      cut -d ' ' -f 1 | \
      xargs -L1 gcloud container builds cancel

    # echo "Delete kube credentials to avoid gcloud/kubectl version mismatch"
    # rm -rf ~/.kube

    echo "- We ignore all fails during cancel (hence the last echo)"


# ----------------------- Taito-cli ----------------------------------

# Preparing steps

- id: ci-prepare
  waitFor: ['-']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-prepare:$BRANCH_NAME', 'server', '$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME']
  env:
    - taito_mode=ci

- id: install
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['install:$BRANCH_NAME']
  env:
    - taito_mode=ci

- id: ci-release-pre
  waitFor: ['install']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-release-pre:$BRANCH_NAME']
  env:
    - taito_mode=ci
    - commit_sha=$COMMIT_SHA

- id: ci-test-unit
  waitFor: ['install']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-test-unit:$BRANCH_NAME']
  env:
    - taito_mode=ci

- id: ci-scan
  waitFor: ['install']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-scan:$BRANCH_NAME']
  env:
    - taito_mode=ci

# Build artifacts

- id: ci-docs
  waitFor: ['install']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-docs:$BRANCH_NAME']
  env:
    - taito_mode=ci

# STACK START

- id: ci-build-client
  waitFor: ['ci-release-pre']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-build:$BRANCH_NAME', 'client', '$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME']
  env:
    - taito_mode=ci

- id: ci-push-client
  waitFor: ['ci-build-client']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-push:$BRANCH_NAME', 'client', '$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME']
  env:
    - taito_mode=ci

- id: ci-build-server
  waitFor: ['ci-release-pre']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-build:$BRANCH_NAME', 'server', '$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME']
  env:
    - taito_mode=ci

- id: ci-push-server
  waitFor: ['ci-build-server']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-push:$BRANCH_NAME', 'server', '$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME']
  env:
    - taito_mode=ci

# STACK END

# Run tests in local environment

# - id: start:local
#   waitFor: ['ci-build-client', 'ci-build-server']
#   name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
#   args: ['start:local']
#   env:
#     - taito_mode=ci
#
# - id: ci-wait:local
#   waitFor: ['ci-build-client', 'ci-build-server']
#   name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
#   args: ['ci-wait:local']
#   env:
#     - taito_mode=ci
#
# - id: ci-test-api:local
#   waitFor: ['ci-wait:local']
#   name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
#   args: ['ci-test-api:local']
#   env:
#     - taito_mode=ci
#     - COMPOSE_PROJECT_NAME=workspace
#
# - id: ci-test-e2e:local
#   waitFor: ['ci-wait:local']
#   name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
#   args: ['ci-test-e2e:local']
#   env:
#     - taito_mode=ci
#     - COMPOSE_PROJECT_NAME=workspace
#
# - id: stop:local
#   waitFor: ['ci-test-api:local', 'ci-test-e2e:local']
#   name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
#   args: ['stop:local']
#   env:
#     - taito_mode=ci

# Deploy to target environment

- id: db-deploy
  waitFor: ['stop:local']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['db-deploy:$BRANCH_NAME']
  env:
    - taito_mode=ci

- id: ci-deploy
  waitFor: ['stop:local']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-deploy:$BRANCH_NAME', '$COMMIT_SHA']
  env:
    - taito_mode=ci

# Run tests against the target environment

- id: ci-wait
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-wait:$BRANCH_NAME']
  env:
    - taito_mode=ci

- id: ci-test-api
  waitFor: ['ci-wait']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-test-api:$BRANCH_NAME']
  env:
    - taito_mode=ci

- id: ci-test-e2e
  waitFor: ['ci-wait']
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-test-e2e:$BRANCH_NAME']
  env:
    - taito_mode=ci

- id: ci-verify
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-verify:$BRANCH_NAME']
  env:
    - taito_mode=ci

# Publish and release

- id: ci-publish
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-publish:$BRANCH_NAME']
  env:
    - taito_mode=ci

- id: ci-release-post
  name: 'eu.gcr.io/gcloud-temp1/github-taitounited-taito-cli/cli:latest'
  args: ['ci-release-post:$BRANCH_NAME']
  env:
    - taito_mode=ci

timeout: 1200s
images: [
  'eu.gcr.io/$PROJECT_ID/$REPO_NAME/client:$COMMIT_SHA',
  'eu.gcr.io/$PROJECT_ID/$REPO_NAME/server:$COMMIT_SHA'
]
