# This file is used to run your application on remote servers with
# Docker Compose. It is not needed if you use Kubernetes or cloud services
# instead.

# TODO: health checks

version: '3.9'
x-logging:
  &default-logging
  options:
    max-size: '100m'
    max-file: '10'
  driver: json-file

services:
  full-stack-template-${taito_env}-ingress:
    container_name: full-stack-template-${taito_env}-ingress
    image: nginx:stable-alpine
    restart: unless-stopped
    logging: *default-logging
    networks:
      - default
    ports:
      - "_PORT_:80"
      # If you want to directly expose this ingress to browser, use the
      # following settings and configure SSL in docker-nginx.conf.
      # - "80:80"
      # - "443:443"
    secrets:
      - BASIC_AUTH_HTPASSWD
    volumes:
      - "./docker-nginx.conf:/etc/nginx/nginx.conf:delegated"

  full-stack-template-${taito_env}-admin:
    container_name: full-stack-template-${taito_env}-admin
    image: local/full-stack-template/admin:_IMAGE_TAG_
    restart: unless-stopped
    logging: *default-logging
    networks:
      - default
    ports:
      - "8080"
    environment:
      # Paths
      REPLACE_BASE_PATH: /admin
      REPLACE_ASSETS_PATH: ${taito_cdn_project_path}/_IMAGE_TAG_/admin
      REPLACE_ASSETS_DOMAIN: '${taito_cdn_domain}'
      # Common variables
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template

  full-stack-template-${taito_env}-client:
    container_name: full-stack-template-${taito_env}-client
    image: local/full-stack-template/client:_IMAGE_TAG_
    restart: unless-stopped
    logging: *default-logging
    networks:
      - default
    ports:
      - "8080"
    secrets:
      # NOTE: Database connection is for tests only
      - DATABASE_PASSWORD
      - EXAMPLE_SECRET
    environment:
      # Paths
      REPLACE_BASE_PATH: ''
      REPLACE_ASSETS_PATH: ${taito_cdn_project_path}/_IMAGE_TAG_/client
      REPLACE_ASSETS_DOMAIN: '${taito_cdn_domain}'
      # Common variables
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template

  full-stack-template-${taito_env}-server:
    container_name: full-stack-template-${taito_env}-server
    image: local/full-stack-template/server:_IMAGE_TAG_
    restart: unless-stopped
    logging: *default-logging
    networks:
      - default
    ports:
      - "8080"
    secrets:
      - DATABASE_PASSWORD
      - REDIS_PASSWORD
      - BUCKET_KEY_SECRET
      - EXAMPLE_SECRET
    environment:
      # Paths and bind
      BASE_PATH: /api
      API_PORT: 8080
      API_BINDADDR: 0.0.0.0
      # Common variables
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template
      COMMON_DEBUG: 'false'
      COMMON_LOG_FORMAT: text
      COMMON_LOG_LEVEL: info      # trace, debug, info, warn, error, fatal
      COMMON_ENV: local
      # Services
      SENTRY_DSN: #sentryDSN
      DATABASE_HOST: 172.17.0.1  # For docker db: full-stack-template-${taito_env}-database
      DATABASE_NAME: ${db_database_name}
      DATABASE_USER: ${db_database_app_username}
      DATABASE_POOL_MIN: '1'
      DATABASE_POOL_MAX: '10'
      REDIS_HOST: full-stack-template-${taito_env}-redis
      REDIS_PORT: 6379
      BUCKET_URL: http://full-stack-template-${taito_env}-storage:9000/
      BUCKET_REGION: milkyway
      BUCKET_BUCKET: bucket
      BUCKET_BROWSE_URL: http://localhost:_PORT_/bucket   # TODO
      BUCKET_DOWNLOAD_URL: http://localhost:_PORT_/bucket # TODO
      BUCKET_KEY_ID: minio
      BUCKET_FORCE_PATH_STYLE: 'true'

  full-stack-template-${taito_env}-www:
    container_name: full-stack-template-${taito_env}-www
    image: local/full-stack-template/www:_IMAGE_TAG_
    restart: unless-stopped
    logging: *default-logging
    networks:
      - default
    ports:
      - "8080"
    environment:
      # Paths
      REPLACE_BASE_PATH: /docs
      REPLACE_ASSETS_PATH: ${taito_cdn_project_path}/_IMAGE_TAG_/www
      REPLACE_ASSETS_DOMAIN: '${taito_cdn_domain}'

  full-stack-template-${taito_env}-redis:
    container_name: full-stack-template-${taito_env}-redis
    image: bitnami/redis:6.0
    restart: unless-stopped
    logging: *default-logging
    networks:
      - default
    ports:
      - "6379"
    secrets:
      - REDIS_PASSWORD
    environment:
      REDIS_PASSWORD_FILE: '/run/secrets/REDIS_PASSWORD'
      REDIS_AOF_ENABLED: 'no'


  # "EXTERNAL RESOURCES"
  # Uncomment these if you want to run them in Docker Compose instead

  # NOTE: If you use full-stack-template-${taito_env}-database instead of external database,
  # do the following:
  # - Uncomment the full-stack-template-${taito_env}-database in this file.
  # - Modify the following settings in taito-config.sh:
  #     db_database_mgr_username="$db_database_app_username"
  #     db_database_mgr_secret="$db_database_app_secret"
  # - In local-ci.sh, move 'db-deploy' step to be executed after the
  #   'deployment-deploy' step, since database must be running during db deploy.
  # - Answer 'no' to the database creation step during 'taito env apply:ENV'.

  # full-stack-template-${taito_env}-database:
  #   container_name: full-stack-template-${taito_env}-database
  #   image: postgres:12
  #   restart: unless-stopped
  #   logging: *default-logging
  #   networks:
  #     - default
  #   ports:
  #     - "5432:5432"
  #   secrets:
  #     - DATABASE_PASSWORD
  #     - DATABASE_MGR_PASSWORD
  #   environment:
  #     POSTGRES_DB: ${db_database_name}
  #     POSTGRES_USER: ${db_database_app_username}
  #     POSTGRES_PASSWORD_FILE: /run/secrets/DATABASE_PASSWORD
  #     MYSQL_ROOT_PASSWORD_FILE /run/secrets/DATABASE_MGR_PASSWORD
  #   volumes:
  #     - "./database:/docker-entrypoint-initdb.d:delegated"
  #     - "./database-db/mount:/var/lib/postgresql/data"

  # "INFRASTRUCTURE"

  # watchtower:
  #   image: index.docker.io/v2tec/watchtower
  #   restart: unless-stopped
  #   logging: *default-logging
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./watchtower-config.json:/config.json
  #   command: --interval 60

secrets:
  DATABASE_PASSWORD:
    file: ./secrets/${taito_env}/${db_database_app_secret}
  DATABASE_MGR_PASSWORD:
    file: ./secrets/${taito_env}/${db_database_mgr_secret}
  REDIS_PASSWORD:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-redis.password
  BUCKET_KEY_SECRET:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-storage.secretKey
  EXAMPLE_SECRET:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-example.secret
  BASIC_AUTH_HTPASSWD:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-basic-auth.auth

networks:
  default:
