# This file is used for running integration tests against a remote
# environment. It is required only if your test implementations require
# a remote database access through a database proxy.

version: '3.5'
services:
  server-template-server-test:
    container_name: server-template-server-test
    image: server-template-server-test:latest
    restart: unless-stopped
    volumes:
      - "./server:/server"
      - "/server/node_modules"
    networks:
      - test
    depends_on:
      - server-template-database
    environment:
      RUNNING_TESTS: "true"

  # taito-cli container serves as a database proxy
  server-template-database:
    container_name: server-template-database
    image: taitounited/taito-cli:latest
    restart: unless-stopped
    entrypoint: /bin/sh -c "cd /project && taito db-proxy:${taito_env} 5432"
    networks:
      - test
    ports:
      - "5432"
    volumes:
      - ".:/project"
      # - "${HOME}/.taito:/root/.taito"
      # - "${HOME}/.ssh:/root/.ssh"
    environment:
      taito_docker: 'true'
      template_default_taito_image: ${template_default_taito_image}
      template_default_organization: ${template_default_organization}
      template_default_domain: ${template_default_domain}
      template_default_domain_prod: ${template_default_domain_prod}
      template_default_zone: ${template_default_zone}
      template_default_zone_prod: ${template_default_zone_prod}
      template_default_provider: ${template_default_provider}
      template_default_provider_org_id: ${template_default_provider_org_id}
      template_default_provider_region: ${template_default_provider_region}
      template_default_provider_zone: ${template_default_provider_zone}
      template_default_provider_billing_account: ${template_default_provider_billing_account}
      template_default_provider_org_id_prod: ${template_default_provider_org_id_prod}
      template_default_provider_region_prod: ${template_default_provider_region_prod}
      template_default_provider_zone_prod: ${template_default_provider_zone_prod}
      template_default_provider_billing_account_prod: ${template_default_provider_billing_account_prod}
      template_default_registry: ${template_default_registry}
      template_default_source_git: ${template_default_source_git}
      template_default_dest_git: ${template_default_dest_git}
      template_default_kubernetes: ${template_default_kubernetes}
      template_default_postgres: ${template_default_postgres}
      template_default_mysql: ${template_default_mysql}

networks:
  test:
