# NOTE: Remove all extra containers that you don't need.

server-template-front:
  container_name: server-template-front
  image: nginx:1.13.3
  restart: on-failure
  ports:
    - "8080:80"
  links:
    - server-template-admin:server-template-admin
    - server-template-client:server-template-client
    - server-template-server:server-template-server
  volumes:
    - "./docker-nginx.conf:/etc/nginx/nginx.conf"

server-template-admin:
  container_name: server-template-admin
  build: ./admin
  dockerfile: ${dockerfile}
  restart: on-failure
  ports:
    - "3334"
  volumes:
    - "./admin:/admin"
    - "/admin/node_modules"
  links:
    - server-template-server:server-template-server
  environment:
    NODE_ENV: development
    COMMON_ENV: local
    API_ROOT: ''
    API_URL: '/api'

server-template-client:
  container_name: server-template-client
  build: ./client
  dockerfile: ${dockerfile}
  restart: on-failure
  ports:
    - "3333"
  volumes:
    - "./client:/client"
    - "/client/node_modules"
  links:
    - server-template-server:server-template-server
  environment:
    NODE_ENV: development
    COMMON_ENV: local
    API_ROOT: ''
    API_URL: '/api'

server-template-server:
  container_name: server-template-server
  build: ./server
  dockerfile: ${dockerfile}
  restart: on-failure
  ports:
    - "3332"
  volumes:
    - "./server:/server"
    - "/server/node_modules"
  links:
    - server-template-cache:server-template-cache
    - server-template-database:server-template-database
    - server-template-bucket:server-template-bucket
  environment:
    NODE_ENV: development
    ENV: dev # TODO remove?
    DEBUG: 'false'
    API_BINDADDR: 0.0.0.0
    API_PORT: 3332
    JWT_SECRET: secret
    ADMIN_PASSWORD: password
    USER_PASSWORD: password
    COMMON_ENV: local
    COMMON_DEBUG: 'true'
    COMMON_PROJECT: server-template
    COMMON_CUSTOMER: customername
    DATABASE_HOST: server-template-database
    DATABASE_ID: server_template_local
    DATABASE_DB: server_template_local
    DATABASE_USER: server_template_local_app
    DATABASE_SECRET: secret
    DATABASE_POOL_MAX: '10'
    BUCKET_HOST: server-template-bucket
    BUCKET_ID: server_template_local
    BUCKET_REGION: europe-west1-c
    BUCKET_PROTOCOL: http
    BUCKET_ACCESS_KEY: 070UEOQR6LX4YPZLFU0V
    BUCKET_SECRET_KEY: CVQVa33NekSiOJGnevSY5ITr8Rql8lFkp22WhLQ+

server-template-cache:
  container_name: server-template-cache
  image: redis
  restart: on-failure
  ports:
    - "6379"

# "EXTERNAL RESOURCES"

server-template-database:
  container_name: server-template-database
  image: postgres:9.6
  restart: on-failure
  ports:
    - "6000:5432"
  environment:
    POSTGRES_DB: server_template_local
    POSTGRES_USER: server_template_local_app
    POSTGRES_PASSWORD: secret
  volumes:
    - "./database:/docker-entrypoint-initdb.d"

server-template-bucket:
  container_name: server-template-bucket
  image: minio/minio
  restart: on-failure
  command: server /export
  ports:
    - "9000"
  environment:
    MINIO_ACCESS_KEY: 070UEOQR6LX4YPZLFU0V
    MINIO_SECRET_KEY: CVQVa33NekSiOJGnevSY5ITr8Rql8lFkp22WhLQ+
