# NOTE: docker-compose taito plugin sets DC_PATH and DC_COMMAND to mitigate
# slow volume mounts on Windows. They might also be used in some other purposes
# in the future.

version: '3.5'
services:
  full-stack-template-ingress:
    container_name: full-stack-template-ingress
    image: nginx:1.15-alpine
    restart: unless-stopped
    networks:
      - default
    ports:
      - "9999:80"
    volumes:
      - "./docker-nginx.conf:/etc/nginx/nginx.conf:delegated"

  full-stack-template-admin:
    container_name: full-stack-template-admin
    build:
      context: ./admin
      dockerfile: ${dockerfile}
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080"
    volumes:
      - "./admin:${DC_PATH}/service:delegated"
      - "./shared:${DC_PATH}/service/shared:delegated"
      - "${DC_PATH}/service/node_modules"
    environment:
      DC_COMMAND: ${DC_COMMAND}
      HOST_UNAME: ${taito_host_uname}
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template
      COMMON_PUBLIC_PORT: 9999
      NODE_ENV: development
      API_ROOT: ''
      API_URL: /api

  full-stack-template-client:
    container_name: full-stack-template-client
    build:
      context: ./client
      dockerfile: ${dockerfile}
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080"
    volumes:
      - "./client:${DC_PATH}/service:delegated"
      - "./shared:${DC_PATH}/service/shared:delegated"
      - "${DC_PATH}/service/node_modules"
    secrets:
      # NOTE: Database connection is for tests only
      - DATABASE_PASSWORD
      - EXAMPLE_SECRET
    environment:
      DC_COMMAND: ${DC_COMMAND}
      HOST_UNAME: ${taito_host_uname}
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template
      COMMON_PUBLIC_PORT: 9999
      NODE_ENV: development
      API_ROOT: ''
      API_URL: /api
      # NOTE: Database connection is for tests only
      DATABASE_HOST: full-stack-template-database
      DATABASE_NAME: ${db_database_name}
      DATABASE_USER: ${db_database_app_username}

  full-stack-template-graphql:
    container_name: full-stack-template-graphql
    build:
      context: ./graphql
      dockerfile: ${dockerfile}
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080"
    volumes:
      - "./graphql:${DC_PATH}/service:delegated"
      - "./shared:${DC_PATH}/service/shared:delegated"
      - "${DC_PATH}/service/node_modules"
    environment:
      DC_COMMAND: ${DC_COMMAND}
      HOST_UNAME: ${taito_host_uname}
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template
      COMMON_PUBLIC_PORT: 9999
      COMMON_DOMAIN: localhost
      COMMON_URL: http://localhost:9999
      COMMON_DEBUG: 'false'
      COMMON_LOG_FORMAT: text
      COMMON_LOG_LEVEL: info      # trace, debug, info, warn, error, fatal
      COMMON_ENV: local
      GRAPHQL_PORT: 8080
      GRAPHQL_BINDADDR: 0.0.0.0
      API_HOST: full-stack-template-server
      API_PORT: 8080

  full-stack-template-server:
    container_name: full-stack-template-server
    build:
      context: ./server
      dockerfile: ${dockerfile}
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080"
    volumes:
      - "./server:${DC_PATH}/service:delegated"
      - "./shared:${DC_PATH}/service/shared:delegated"
      - "${DC_PATH}/service/node_modules"
    secrets:
      - DATABASE_PASSWORD
      - S3_KEY_SECRET
      - EXAMPLE_SECRET
    environment:
      DC_COMMAND: ${DC_COMMAND}
      HOST_UNAME: ${taito_host_uname}
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template
      COMMON_PUBLIC_PORT: 9999
      COMMON_DEBUG: 'false'
      COMMON_LOG_FORMAT: text
      COMMON_LOG_LEVEL: info      # trace, debug, info, warn, error, fatal
      COMMON_ENV: local
      SENTRY_DSN: #sentryDSN
      API_PORT: 8080
      API_BINDADDR: 0.0.0.0
      KAFKA_HOST: full-stack-template-kafka
      KAFKA_PORT: 9092
      DATABASE_HOST: full-stack-template-database
      DATABASE_NAME: ${db_database_name}
      DATABASE_USER: ${db_database_app_username}
      DATABASE_POOL_MIN: '1'
      DATABASE_POOL_MAX: '10'
      S3_URL: http://full-stack-template-storage:9000/
      S3_REGION: milkyway
      S3_BUCKET: bucket
      S3_KEY_ID: minio

  full-stack-template-www:
    container_name: full-stack-template-www
    build:
      context: ./www
      dockerfile: ${dockerfile}
    restart: unless-stopped
    networks:
      - default
    ports:
      # TODO: Temporary hack for https://github.com/gatsbyjs/gatsby/issues/3721
      - "7463:8080"
    volumes:
      - "./www:${DC_PATH}/service:delegated"
      - "${DC_PATH}/service/node_modules"
      - "${DC_PATH}/service/site/node_modules" # FOR GATSBY ONLY
      # FOR GATSBY ONLY:
      # - "/service/site/node_modules"
    environment:
      DC_COMMAND: ${DC_COMMAND}
      HOST_UNAME: ${taito_host_uname}
      COMMON_PUBLIC_PORT: 9999

  full-stack-template-redis:
    container_name: full-stack-template-redis
    image: redis:5.0-alpine
    restart: unless-stopped
    networks:
      - default
    ports:
      - "6379"

  full-stack-template-kafka:
    container_name: full-stack-template-kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=full-stack-template-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  full-stack-template-zookeeper:
    container_name: full-stack-template-zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # "EXTERNAL RESOURCES"

  full-stack-template-database:
    container_name: full-stack-template-database
    image: postgres:9.6
    restart: unless-stopped
    networks:
      - default
    ports:
      - "6000:5432"
    secrets:
      - DATABASE_PASSWORD
    environment:
      POSTGRES_DB: ${db_database_name}
      POSTGRES_USER: ${db_database_app_username}
      POSTGRES_PASSWORD_FILE: /run/secrets/DATABASE_PASSWORD
    volumes:
      - "./database:/docker-entrypoint-initdb.d:delegated"

  full-stack-template-storage:
    container_name: full-stack-template-storage
    build:
      context: ./storage
      dockerfile: ${dockerfile}
    restart: unless-stopped
    command: server /service
    networks:
      - default
    ports:
      - "9000"
    secrets:
      - S3_KEY_SECRET
    environment:
      MINIO_ACCESS_KEY: minio
      # MINIO requires key as environment variable?
      MINIO_SECRET_KEY: secret1234

secrets:
  DATABASE_PASSWORD:
    file: ./secrets/${taito_env}/${db_database_app_secret}
  S3_KEY_SECRET:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-storage-gateway.secret
  EXAMPLE_SECRET:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-example.secret

networks:
  default:

# EOF
