# This file is used for running Docker Compose on remote servers. It is not
# needed if you use Kubernetes instead.
# TODO: health checks

version: '3.5'
services:
  full-stack-template-ingress:
    container_name: full-stack-template-ingress
    image: nginx:1.17-alpine
    restart: unless-stopped
    networks:
      - default
    ports:
      - "_PORT_:80"
      # If you want to directly expose this ingress to browser, use the
      # following settings and configure SSL in docker-nginx.conf.
      # - "80:80"
      # - "443:443"
    secrets:
      - BASIC_AUTH_HTPASSWD
    volumes:
      - "./docker-nginx.conf:/etc/nginx/nginx.conf:delegated"

  full-stack-template-admin:
    container_name: full-stack-template-admin
    image: local/full-stack-template/admin:_IMAGE_TAG_
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080"
    environment:
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template

  full-stack-template-client:
    container_name: full-stack-template-client
    image: local/full-stack-template/client:_IMAGE_TAG_
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080"
    secrets:
      # NOTE: Database connection is for tests only
      - DATABASE_PASSWORD
      - EXAMPLE_SECRET
    environment:
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template

  full-stack-template-graphql:
    container_name: full-stack-template-graphql
    image: local/full-stack-template/graphql:_IMAGE_TAG_
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080"
    environment:
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template
      COMMON_DOMAIN: localhost
      COMMON_URL: http://localhost:_PORT_
      COMMON_DEBUG: 'false'
      COMMON_LOG_FORMAT: text
      COMMON_LOG_LEVEL: info      # trace, debug, info, warn, error, fatal
      COMMON_ENV: local
      GRAPHQL_PORT: 8080
      GRAPHQL_BINDADDR: 0.0.0.0
      API_HOST: full-stack-template-server
      API_PORT: 8080

  full-stack-template-server:
    container_name: full-stack-template-server
    image: local/full-stack-template/server:_IMAGE_TAG_
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080"
    secrets:
      - DATABASE_PASSWORD
      - S3_KEY_SECRET
      - EXAMPLE_SECRET
    environment:
      COMMON_COMPANY: companyname
      COMMON_PROJECT: full-stack-template
      COMMON_DEBUG: 'false'
      COMMON_LOG_FORMAT: text
      COMMON_LOG_LEVEL: info      # trace, debug, info, warn, error, fatal
      COMMON_ENV: local
      SENTRY_DSN: #sentryDSN
      API_PORT: 8080
      API_BINDADDR: 0.0.0.0
      KAFKA_HOST: full-stack-template-kafka
      KAFKA_PORT: 9092
      DATABASE_HOST: 172.17.0.1  # For docker db: full-stack-template-database
      DATABASE_NAME: ${db_database_name}
      DATABASE_USER: ${db_database_app_username}
      DATABASE_POOL_MIN: '1'
      DATABASE_POOL_MAX: '10'
      S3_URL: http://full-stack-template-storage:9000/
      S3_REGION: milkyway
      S3_BUCKET: bucket
      S3_KEY_ID: minio
      S3_FORCE_PATH_STYLE: 'true'

  full-stack-template-www:
    container_name: full-stack-template-www
    image: local/full-stack-template/www:_IMAGE_TAG_
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080"

  full-stack-template-redis:
    container_name: full-stack-template-redis
    image: redis:5.0-alpine
    restart: unless-stopped
    networks:
      - default
    ports:
      - "6379"

  # "EXTERNAL RESOURCES"
  # Uncomment these if you want to run them in Docker Compose instead

  full-stack-template-kafka:
    container_name: full-stack-template-kafka
    image: 'bitnami/kafka:latest'
    ports:
      - '9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=full-stack-template-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  full-stack-template-zookeeper:
    container_name: full-stack-template-zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # NOTE: If you use full-stack-template-database instead of external database,
  # do the following:
  # - Uncomment the full-stack-template-database in this file.
  # - Modify the following settings in taito-config.sh:
  #     db_database_mgr_username="$db_database_app_username"
  #     db_database_mgr_secret="$db_database_app_secret"
  # - In local-ci.sh, move 'db-deploy' step to be executed after the
  #   'deployment-deploy' step, since database must be running during db deploy.
  # - Answer 'no' to the database creation step during 'taito env apply:ENV'.

  # full-stack-template-database:
  #   container_name: full-stack-template-database
  #   image: postgres:9.6
  #   restart: unless-stopped
  #   networks:
  #     - default
  #   ports:
  #     - "5432:5432"
  #   secrets:
  #     - DATABASE_PASSWORD
  #   environment:
  #     POSTGRES_DB: ${db_database_name}
  #     POSTGRES_USER: ${db_database_app_username}
  #     POSTGRES_PASSWORD_FILE: /run/secrets/DATABASE_PASSWORD
  #   volumes:
  #     - "./database:/docker-entrypoint-initdb.d:delegated"
  #     - "./database-db/mount:/var/lib/postgresql/data"

  # "INFRASTRUCTURE"

  # watchtower:
  #   restart: always
  #   image: index.docker.io/v2tec/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./watchtower-config.json:/config.json
  #   command: --interval 60

secrets:
  DATABASE_PASSWORD:
    file: ./secrets/${taito_env}/${db_database_app_secret}
  S3_KEY_SECRET:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-storage.secretKey
  EXAMPLE_SECRET:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-example.secret
  BASIC_AUTH_HTPASSWD:
    file: ./secrets/${taito_env}/${taito_project}-${taito_env}-basic-auth.auth

networks:
  default:
