# This file is used for running integration tests against a remote
# environment. It is required only if your test implementations require
# a remote database access through a database proxy.

version: '3.5'
services:
  server-template-client-test:
    container_name: server-template-client-test
    image: server-template-client-test:latest
    restart: unless-stopped
    volumes:
      - "./client:/service:delegated"
      - "./shared:/service/shared:delegated"
      - "/service/node_modules"
      # NOTE: for flow
      # - "/service/flow-typed/npm"
    networks:
      - test
    depends_on:
      - server-template-database-test-proxy
    environment:
      taito_running_tests: "true"

  server-template-server-test:
    container_name: server-template-server-test
    image: server-template-server-test:latest
    restart: unless-stopped
    volumes:
      - "./server:/service:delegated"
      - "./shared:/service/shared:delegated"
      - "/service/node_modules"
      # NOTE: for flow
      # - "/service/flow-typed/npm"
    networks:
      - test
    depends_on:
      - server-template-database-test-proxy
    environment:
      taito_running_tests: "true"

  # Taito CLI container serves as a database proxy
  server-template-database-test-proxy:
    container_name: server-template-database-test-proxy
    image: taitounited/taito-cli:latest
    restart: unless-stopped
    entrypoint: /bin/sh -c "cd /project && taito db-proxy:${taito_env} 5432"
    user: taito
    networks:
      - test
    ports:
      - "5432"
    volumes:
      - ".:/project:delegated"
    environment:
      taito_docker: 'true'
      template_default_taito_image: ${template_default_taito_image}
      template_default_organization: ${template_default_organization}
      template_default_organization_abbr: ${template_default_organization_abbr}
      template_default_github_organization: ${template_default_github_organization}
      template_default_sentry_organization: ${template_default_sentry_organization}
      template_default_domain: ${template_default_domain}
      template_default_domain_prod: ${template_default_domain_prod}
      template_default_zone: ${template_default_zone}
      template_default_zone_prod: ${template_default_zone_prod}
      template_default_provider: ${template_default_provider}
      template_default_provider_org_id: ${template_default_provider_org_id}
      template_default_provider_region: ${template_default_provider_region}
      template_default_provider_zone: ${template_default_provider_zone}
      template_default_provider_org_id_prod: ${template_default_provider_org_id_prod}
      template_default_provider_region_prod: ${template_default_provider_region_prod}
      template_default_provider_zone_prod: ${template_default_provider_zone_prod}
      template_default_registry: ${template_default_registry}
      template_default_source_git: ${template_default_source_git}
      template_default_dest_git: ${template_default_dest_git}
      template_default_kubernetes: ${template_default_kubernetes}
      template_default_postgres: ${template_default_postgres}
      template_default_mysql: ${template_default_mysql}

networks:
  test:
