# This file is used for running integration tests against a remote
# environment. It is needed only if your test implementations require
# a remote database access through a proxy, or secrets defined in the remote
# environment.

version: '3.5'
services:
  full-stack-template-admin-test:
    container_name: full-stack-template-admin-test
    image: full-stack-template-admin-test:latest
    restart: unless-stopped
    volumes:
      - "./admin:/service:delegated"
      - "./shared:/service/shared:delegated"
      - "/service/node_modules"
    network_mode: "bridge"
    secrets:
      - DATABASE_PASSWORD
    environment:
      taito_running_tests: "true"

  full-stack-template-client-test:
    container_name: full-stack-template-client-test
    image: full-stack-template-client-test:latest
    restart: unless-stopped
    volumes:
      - "./client:/service:delegated"
      - "./shared:/service/shared:delegated"
      - "/service/node_modules"
    network_mode: "bridge"
    secrets:
      - DATABASE_PASSWORD
    environment:
      taito_running_tests: "true"

  full-stack-template-graphql-test:
    container_name: full-stack-template-graphql-test
    image: full-stack-template-graphql-test:latest
    restart: unless-stopped
    volumes:
      - "./graphql:/service:delegated"
      - "./shared:/service/shared:delegated"
      - "/service/node_modules"
    network_mode: "bridge"
    secrets:
      - DATABASE_PASSWORD
    environment:
      taito_running_tests: "true"

  full-stack-template-server-test:
    container_name: full-stack-template-server-test
    image: full-stack-template-server-test:latest
    restart: unless-stopped
    volumes:
      - "./server:/service:delegated"
      - "./shared:/service/shared:delegated"
      - "/service/node_modules"
    links:
      - full-stack-template-database-test-proxy
      # - full-stack-template-services-test-proxy
    network_mode: "bridge"
    secrets:
      - DATABASE_PASSWORD
    environment:
      taito_running_tests: "true"

  # Taito CLI container serves as a database proxy
  full-stack-template-database-test-proxy:
    container_name: full-stack-template-database-test-proxy
    image: ${taito_image}
    restart: unless-stopped
    user: taito
    entrypoint:
      - /bin/sh
      - -c
      - |
        cd /project
        taito db proxy:${taito_env} 5432
    ports:
      - "5432"
    network_mode: "bridge"
    volumes:
      - ".:/project:delegated"
    environment:
      taito_docker: 'true'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: ${taito_proxy_credentials_file}
      template_default_taito_image: ${template_default_taito_image}
      template_default_environments: ${template_default_environments}
      template_default_organization: ${template_default_organization}
      template_default_organization_abbr: ${template_default_organization_abbr}
      template_default_vc_organization: ${template_default_vc_organization}
      template_default_vc_url: ${template_default_vc_url}
      template_default_sentry_organization: ${template_default_sentry_organization}
      template_default_domain: ${template_default_domain}
      template_default_domain_prod: ${template_default_domain_prod}
      template_default_zone: ${template_default_zone}
      template_default_zone_prod: ${template_default_zone_prod}
      template_default_provider: ${template_default_provider}
      template_default_provider_org_id: ${template_default_provider_org_id}
      template_default_provider_region: ${template_default_provider_region}
      template_default_provider_zone: ${template_default_provider_zone}
      template_default_provider_org_id_prod: ${template_default_provider_org_id_prod}
      template_default_provider_region_prod: ${template_default_provider_region_prod}
      template_default_provider_zone_prod: ${template_default_provider_zone_prod}
      template_default_uptime_channels_prod: ${template_default_uptime_channels_prod}
      template_default_container_registry: ${template_default_container_registry}
      template_default_source_git: ${template_default_source_git}
      template_default_dest_git: ${template_default_dest_git}
      template_default_kubernetes: ${template_default_kubernetes}
      template_default_postgres: ${template_default_postgres}
      template_default_mysql: ${template_default_mysql}

  # Taito CLI container serves as a tcp proxy for redis, etc.
  # full-stack-template-services-test-proxy:
  #   container_name: full-stack-template-services-test-proxy
  #   image: ${taito_image}
  #   restart: unless-stopped
  #   user: taito
  #   entrypoint:
  #     - /bin/sh
  #     - -c
  #     - |
  #       cd /project
  #       taito forward:redis:${taito_env} 6379
  #       # TIP: you can define multiple forwards like this:
  #       # taito forward:kafka:${taito_env} 9092 &
  #       # taito forward:redis:${taito_env} 6379 &
  #       # tail -f /dev/null
  #   ports:
  #     - "6379"
  #   network_mode: "bridge"
  #   volumes:
  #     - ".:/project:delegated"
  #   environment:
  #     taito_docker: "true"
  #     AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  #     AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  #     GOOGLE_APPLICATION_CREDENTIALS: ${taito_proxy_credentials_file}

secrets:
  DATABASE_PASSWORD:
    file: ./tmp/secrets/${taito_env}/${db_database_app_secret}
