SET taito_host_uname=""
SET dockerfile="Dockerfile"
SET taito_env="local"
SET taito_project="full-stack-template"
SET db_database_name="full_stack_template_local"
SET db_database_app_username="full_stack_template_local_app"
SET db_database_app_secret="full-stack-template-local-db-app.password"
