# Swagger: http://swagger.io/docs/specification/what-is-swagger/

# NOTE: Swagger is optional. Alternatively you can just copy paste json
# examples in a markdown file and add some documentation.

# NOTE: Concentrate especially on defining request parameters and response codes
# (OK, not found, ...). Describing response content is not that important,
# since api user can browse the returned response himself.

# TODO Create swagger definitions with some tool that supports generating
#   Swagger definitions from json? API2Swagger?
# TODO Use Swagger for request validation?
# TODO Deploy swagger-ui: helps developers, testers, etc. Supports calling
#   real APIs?

info:
  title: server-template API
  description: TODO.
  termsOfService: TODO
  contact:
    name: Taito United
    url: http://www.taitounited.fi
    email: 'support@taitounited.fi'
host: TODO
schemes:
  - https
basePath: /api
consumes:
  - application/json
produces:
  - application/json

definitions:
  Error:
    type: object
    required:
      - statusCode
      - error
      - message
    properties:
      statusCode:
        type: integer
        format: int32
        description: HTTP status code.
      error:
        type: string
        description: General error name.
      message:
        type: string
        description: Descriptive error message.
      causes:
        type: object
        description: |
          Error causes, meant for making programming error handling easier
          in API client code. Example: `CLIENT_NOT_FOUND: true`.
        additionalProperties:
          type: string
          description: Error specific.
