---
extends:
  - airbnb-base
  - prettier

env:
  node: true
  es6: true
  mocha: true

parser: "babel-eslint"

parserOptions:
  ecmaVersion: 2017

plugins:
  - prettier

# 0: off, 1: warning, 2: error
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
  arrow-parens: [2, "as-needed"]
  # single quotes
  quotes: [2, "single"]
  jsx-quotes: [2, "prefer-single"]
  # 2 space indentation
  # indent: [2, 2]
  # Allow _function/variable names (to show privateness)
  no-underscore-dangle: 0
  # Commas always at the end of line
  comma-style: [2, "last"]
  comma-dangle: ["error", {
    "arrays": "only-multiline",
    "objects": "only-multiline",
    "imports": "only-multiline",
    "exports": "only-multiline",
    "functions": "ignore",
  }]
  # 80 char line length
  max-len: [2, 80, 1]
  # console is fine
  no-console: 0

  # allow assigning to function params because of koa ctx.body
  no-param-reassign: 0
  # allow empty block statements, useful for catching sometimes
  no-empty: 0

  # returning JSON from arrow functions without a return statement breaks the
  # parser, and having a single return statement is not allowed by this rule...
  arrow-body-style: 0
  no-confusing-arrow: 0
  class-methods-use-this: 0
  quote-props: 0
  generator-star-spacing: 0
  babel/generator-star-spacing: 0
  import/extensions: 0
  new-cap: 0
