FROM node:8.5-alpine

ARG BUILD_VERSION
ARG BUILD_IMAGE_TAG

ENV BUILD_VERSION ${BUILD_VERSION}
ENV BUILD_IMAGE_TAG ${BUILD_IMAGE_TAG}
ENV NODE_ENV development

RUN apk add --update-cache build-base python git fontconfig

WORKDIR /app

COPY ./package.json /app/package.json
RUN npm install --loglevel warn

COPY . /app

RUN npm run build:prod

# TODO Remove obsolete files
# RUN rm -rf ./*/
# RUN npm install --only=dev

EXPOSE 3332

ENV NODE_ENV production

CMD ["npm", "run", "start:prod"]
