rbac:
  create: true
serviceAccount:
  create: true
podSecurityPolicy:
  enabled: true

ingress:
  class: nginx
  tls: true
  maxBodySize: 1m
  basicAuth:
    enabled: true
    htpasswdSecret:
  domains:

serviceDefaults:
  # Basics
  image: # For 3rd party container image
  command:
  path:
  port: 8080
  tier:
  livenessPath: /healthz
  # Security
  runAsUser:
  fsGroup:
  # Resources
  cpuRequest: 2m
  cpuLimit: 100m
  memoryRequest: 50Mi
  memoryLimit: 256Mi
  # Scaling
  replicas: 1
  autoscale: false
  minReplicas: 2
  maxReplicas: 5
  # TODO metrics:
  # https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
  # TODO vertical autoscaling:
  # https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling
  # Env
  env:
    # Environment variables
  secrets:
    # Secrets

services:
