import config from '../../src/common/config';

const testConfig = {
  // Database
  DATABASE_HOST: config.DATABASE_HOST,
  DATABASE_PORT: config.DATABASE_PORT,
  DATABASE_NAME: config.DATABASE_NAME,
  DATABASE_USER: config.DATABASE_USER,
  DATABASE_PASSWORD: config.DATABASE_PASSWORD,
  DATABASE_POOL_MAX: config.DATABASE_POOL_MAX,
  DATABASE_SSL_ENABLED: config.DATABASE_SSL_ENABLED,
  DATABASE_SSL_CLIENT_CERT_ENABLED: config.DATABASE_SSL_CLIENT_CERT_ENABLED,
  DATABASE_SSL_CA: config.DATABASE_SSL_CA,
  DATABASE_SSL_CERT: config.DATABASE_SSL_CERT,
  DATABASE_SSL_KEY: config.DATABASE_SSL_KEY,
};

export default testConfig;
