import { defineConfig, type DummyRuleMap } from 'oxlint';
import commonConfig from '../.oxlintrc.json' with { type: 'json' };

function config() {
  return defineConfig({
    // @ts-expect-error JSON files cannot be imported as `const`.
    extends: [commonConfig],
    plugins: [
      'eslint',
      'import',
      'node',
      'oxc',
      'promise',
      'typescript',
      'unicorn',
    ],
    env: {
      builtin: true,
    },
    ignorePatterns: ['node_modules', 'build', 'shared'],
    rules: {
      ...coreRules,
      ...oxcRules,
      ...importRules,
      ...nodeRules,
      ...promiseRules,
      ...unicornRules,
    },
  });
}

const coreRules: DummyRuleMap = {
  'constructor-super': 'error',
  'func-style': ['error', 'declaration'],
  'for-direction': 'error',
  'getter-return': 'error',
  'no-array-constructor': 'error',
  'no-async-promise-executor': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-const-assign': 'error',
  'no-constant-binary-expression': 'error',
  'no-constant-condition': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty-character-class': 'error',
  'no-empty-pattern': 'error',
  'no-empty-static-block': 'error',
  'no-empty': 'error',
  'no-ex-assign': 'error',
  'no-extra-boolean-cast': 'error',
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-import-assign': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-loss-of-precision': 'error',
  'no-misleading-character-class': 'error',
  'no-new-native-nonconstructor': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-obj-calls': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-self-assign': 'error',
  'no-setter-return': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-this-before-super': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unsafe-optional-chaining': 'error',
  'no-unused-expressions': 'error',
  'no-unused-labels': 'error',
  'no-unused-private-class-members': 'error',
  'no-unused-vars': [
    'error',
    {
      argsIgnorePattern: '^_',
      caughtErrorsIgnorePattern: '^_',
      destructuredArrayIgnorePattern: '^_',
    },
  ],
  'no-useless-backreference': 'error',
  'no-useless-catch': 'error',
  'no-useless-escape': 'error',
  'no-with': 'error',
  'no-use-before-define': 'off',
  'require-yield': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',
  'accessor-pairs': 'error',
  'array-callback-return': 'error',
  eqeqeq: 'error',
  'no-alert': 'error',
  'no-constructor-return': 'error',
  'no-empty-function': 'error',
  'no-eq-null': 'error',
  'no-extra-bind': 'error',
  'no-loop-func': 'error',
  'no-new': 'error',
  'no-new-wrappers': 'error',
  'no-object-constructor': 'error',
  'no-param-reassign': 'error',
  'no-promise-executor-return': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-shadow': 'error',
  'no-throw-literal': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-return': 'error',
  'no-var': 'error',
  'prefer-const': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  radix: 'error',
  'require-await': 'error',
};

const oxcRules: DummyRuleMap = {
  'oxc/bad-array-method-on-arguments': 'error',
  'oxc/bad-char-at-comparison': 'error',
  'oxc/bad-comparison-sequence': 'error',
  'oxc/bad-min-max-func': 'error',
  'oxc/bad-object-literal-comparison': 'error',
  'oxc/bad-replace-all-arg': 'error',
  'oxc/const-comparisons': 'error',
  'oxc/double-comparisons': 'error',
  'oxc/erasing-op': 'error',
  'oxc/missing-throw': 'error',
  'oxc/number-arg-out-of-range': 'error',
  'oxc/only-used-in-recursion': 'error',
  'oxc/uninvoked-array-callback': 'error',
};

const importRules: DummyRuleMap = {
  'import/namespace': 'error',
  'import/default': 'error',
  'import/no-named-as-default': 'error',
  'import/no-named-as-default-member': 'error',
  'import/no-duplicates': 'error',
};

const nodeRules: DummyRuleMap = {
  'node/callback-return': 'error',
  'node/exports-style': 'error',
  'node/global-require': 'error',
  'node/handle-callback-err': 'error',
  'node/no-exports-assign': 'error',
  'node/no-mixed-requires': 'error',
  'node/no-new-require': 'error',
  'node/no-path-concat': 'error',
  'node/no-process-env': 'error',
  'node/no-sync': 'error',
  'node/no-top-level-await': 'error',
};

const promiseRules: DummyRuleMap = {
  'promise/always-return': 'error',
  'promise/no-return-wrap': 'error',
  'promise/param-names': 'error',
  'promise/catch-or-return': 'error',
  'promise/no-nesting': 'error',
  'promise/no-promise-in-callback': 'error',
  'promise/no-callback-in-promise': 'error',
  'promise/no-new-statics': 'error',
  'promise/valid-params': 'error',
};

const unicornRules: DummyRuleMap = {
  'unicorn/no-await-in-promise-methods': 'error',
  'unicorn/no-empty-file': 'error',
  'unicorn/no-invalid-fetch-options': 'error',
  'unicorn/no-invalid-remove-event-listener': 'error',
  'unicorn/no-new-array': 'error',
  'unicorn/no-single-promise-in-promise-methods': 'error',
  'unicorn/no-thenable': 'error',
  'unicorn/no-unnecessary-await': 'error',
  'unicorn/no-useless-fallback-in-spread': 'error',
  'unicorn/no-useless-length-check': 'error',
  'unicorn/no-useless-spread': 'error',
  'unicorn/prefer-set-size': 'error',
  'unicorn/prefer-string-starts-ends-with': 'error',
};

export default config();
