apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}-ingress
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.maxBodySize | quote }}
{{- if .Values.ingress.basicAuth }}
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-realm: {{ .Chart.Name | quote }}
    ingress.kubernetes.io/auth-secret: {{ template "name" . }}-basic-auth
{{- end -}}
{{ if .Values.ingress.tls }}
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
{{ end }}
    # NOTE: see https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md
    # TODO ingress.kubernetes.io/limit-connections
    # TODO ingress.kubernetes.io/limit-rps
spec:
{{ if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ template "fullname" . -}} .taitodev.com
    secretName: {{ template "fullname" . }}-ssl

  {{- range $domain := .Values.domains }}
  - hosts:
    - {{ $domain }}
    secretName: {{ $domain }}-ssl
  {{- end -}}

{{ end }}
  rules:
    - host: {{ template "fullname" . -}} .taitodev.com
      http:
        paths:
          {{ if .Values.stack.server }}
          - path: {{ .Values.server.path | quote }}
            backend:
              serviceName: {{ template "name" . }}-{{ .Values.stack.server }}
              servicePort: {{ .Values.server.port }}
          {{ end }}
          {{ if and (.Values.stack.bot) (.Values.bot.path) }}
          - path: {{ .Values.bot.path | quote }}
            backend:
              serviceName: {{ template "name" . }}-{{ .Values.stack.bot }}
              servicePort: {{ .Values.bot.port }}
          {{ end }}
          {{ if .Values.stack.admin }}
          - path: {{ .Values.admin.path | quote }}
            backend:
              serviceName: {{ template "name" . }}-{{ .Values.stack.admin }}
              servicePort: {{ .Values.admin.port }}
          {{ end }}
          {{ if .Values.stack.client }}
          - path: {{ .Values.client.path | quote }}
            backend:
              serviceName: {{ template "name" . }}-{{ .Values.stack.client }}
              servicePort: {{ .Values.client.port }}
          {{ end }}
    {{- $root := . -}}
    {{- range $domain := .Values.domains }}
    - host: {{ $domain }}
      http:
        paths:
          {{ if $root.Values.stack.server }}
          - path: {{ $root.Values.server.path | quote }}
            backend:
              serviceName: {{ template "name" . }}-{{ $root.Values.stack.server }}
              servicePort: {{ $root.Values.server.port }}
          {{ end }}
          {{ if and ($root.Values.stack.bot) ($root.Values.bot.path) }}
          - path: {{ $root.Values.bot.path | quote }}
            backend:
              serviceName: {{ template "name" . }}-{{ $root.Values.stack.bot }}
              servicePort: {{ $root.Values.bot.port }}
          {{ end }}
          {{ if $root.Values.stack.admin }}
          - path: {{ $root.Values.admin.path | quote }}
            backend:
              serviceName: {{ template "name" . }}-{{ $root.Values.stack.admin }}
              servicePort: {{ $root.Values.admin.port }}
          {{ end }}
          {{ if $root.Values.stack.client }}
          - path: {{ $root.Values.client.path | quote }}
            backend:
              serviceName: {{ template "name" . }}-{{ $root.Values.stack.client }}
              servicePort: {{ $root.Values.client.port }}
          {{ end }}
    {{- end -}}
