{{ if .Values.stack.admin }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-{{ .Values.stack.admin }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    tier: frontend
    role: admin
  ports:
    - port: {{ .Values.admin.port }}
{{ end }}

{{ if .Values.stack.client }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-{{ .Values.stack.client }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    tier: frontend
    role: client
  ports:
    - port: {{ .Values.client.port }}
{{ end }}

{{ if .Values.stack.server }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-{{ .Values.stack.server }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    tier: backend
    role: server
  ports:
    - port: {{ .Values.server.port }}
{{ end }}

{{ if .Values.stack.bot }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-{{ .Values.stack.bot }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    tier: backend
    role: bot
  ports:
    - port: {{ .Values.bot.port }}
{{ end }}

{{ if .Values.stack.cache }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-{{ .Values.stack.cache }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    tier: backend
    role: cache
  ports:
    - port: {{ .Values.cache.port }}
{{ end }}

{{ if .Values.stack.queue }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-{{ .Values.stack.queue }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    tier: backend
    role: queue
  ports:
    - port: {{ .Values.queue.port }}
{{ end }}

{{ if and (.Values.stack.database) (eq .Values.env "local") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-{{ .Values.stack.database }}
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    tier: backend
    role: database
  ports:
    - port: {{ .Values.database.port }}
{{ end }}

{{ if .Values.stack.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-{{ .Values.stack.storage }}
spec:
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
    tier: backend
    role: storage
  ports:
    - port: {{ .Values.storage.port }}
{{ end }}
