# Tips for PR environments:
#
# You can use the following preconfigured labels to adjust the pull request:
#
# - "PR - has env": The pull request environment is left running after the CI/CD pipeline
#   execution. This is useful if you need to get feedback from designers, customers, or
#   testing personnel.
#
# - "PR - use dev db": The pull request uses dev database instead of it's own
#   database. This is useful, if testing personnel does testing in pull request
#   environments and they want to preserve data while hopping between the
#   pull-requests.
#
# - "PR - db recreate": The pull-request will recreate the target env (dev) database
#   once merged. This is useful, if you know that your database migrations include
#   breaking changes. Note that you shouldn't use this label anymore, once the
#   application has been released to production.
#
# - "PR - high resources": The pull-request environment has multiple server replicas
#   and higher cpu/mem resource limits than a normal PR environment. You can fine
#   tune these settings in scripts/helm-pr-high-resources.yaml.

name: CI/CD Pipeline
on:
  push:
    branches: ["dev", "test", "qa", "demo", "stag", "canary", "prod"]
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - dev

env:
  NODE_VERSION: "22.12.0"

jobs:
  changes:
    name: Check changes
    runs-on: ${{ vars.BUILD_RUNS_ON || 'gcp-proto-vm' }}
    outputs:
      client: ${{ github.event_name != 'pull_request' && 'true' || steps.filter.outputs.client }}
      server: ${{ github.event_name != 'pull_request' && 'true' || steps.filter.outputs.server }}
      playwright: ${{ github.event_name != 'pull_request' && 'true' || steps.filter.outputs.playwright }}
      any: ${{ github.event_name != 'pull_request' && 'true' || steps.filter.outputs.any }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        if: github.event_name == 'pull_request'
        with:
          filters: |
            client: &client
              - client/**
              - shared/**
              - '!**/*.md'
            server: &server
              - server/**
              - shared/**
              - '!**/*.md'
            playwright: &playwright
              - playwright/**
              - '!**/*.md'
            any:
              - *client
              - *server
              - *playwright

  pr-checks:
    name: PR checks
    runs-on: ${{ vars.BUILD_RUNS_ON || 'gcp-proto-vm' }}
    needs: changes
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        path: [client, server, playwright]
    steps:
      - name: Checkout repository
        if: needs.changes.outputs[matrix.path] == 'true'
        uses: actions/checkout@v4

      - name: Setup Node.js
        if: needs.changes.outputs[matrix.path] == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        if: needs.changes.outputs[matrix.path] == 'true'
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ${{ matrix.path }}/node_modules
          key: ${{ runner.os }}-${{ matrix.path }}-node-${{ env.NODE_VERSION }}-${{ hashFiles(format('{0}/package-lock.json', matrix.path)) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.path }}-node-${{ env.NODE_VERSION }}-
            ${{ runner.os }}-${{ matrix.path }}-node-

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true' && needs.changes.outputs[matrix.path] == 'true'
        working-directory: ${{ matrix.path }}
        run: npm ci

      - name: Codegen
        if: matrix.path != 'playwright' && needs.changes.outputs[matrix.path] == 'true'
        working-directory: ${{ matrix.path }}
        run: npm run generate

      - name: Check translations
        if: matrix.path == 'client' && needs.changes.outputs[matrix.path] == 'true'
        working-directory: ${{ matrix.path }}
        run: npm run translations:validate

      - name: Lint
        if: needs.changes.outputs[matrix.path] == 'true'
        working-directory: ${{ matrix.path }}
        run: npm run lint

      - name: Typecheck
        if: needs.changes.outputs[matrix.path] == 'true'
        working-directory: ${{ matrix.path }}
        run: npm run typecheck

      - name: Check formatting
        if: needs.changes.outputs[matrix.path] == 'true'
        working-directory: ${{ matrix.path }}
        run: npm run format:check

      - name: Unit test
        if: matrix.path == 'client' && needs.changes.outputs.client == 'true'
        working-directory: ${{ matrix.path }}
        run: npm run test:unit # server unit tests are run in test-server job

      - name: Ensure build
        if: matrix.path != 'playwright' && needs.changes.outputs[matrix.path] == 'true'
        working-directory: ${{ matrix.path }}
        run: npm run build

  prepare-storybook:
    name: Prepare storybook
    needs: changes
    if: needs.changes.outputs.client == 'true'
    runs-on: ${{ vars.BUILD_RUNS_ON || 'gcp-proto-vm' }}
    timeout-minutes: 15
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
      ENV: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Prepare Storybook container image for deployment
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: >
            artifact
            prepare:storybook:${{env.ENV}}
            ${{ env.IMAGE_TAG }}
            ""
            false
            ./client
            ./client
            Dockerfile.storybook

  # NOTE: if client, server, or playwright have changes we need to prepare all
  # of them as changes in any of them forces us to rerun Playwright tests
  # which rely on the client and server being prepared and deployed etc.

  prepare-client:
    name: Prepare client
    needs: changes
    if: needs.changes.outputs.any == 'true'
    runs-on: ${{ vars.BUILD_RUNS_ON || 'gcp-proto-vm' }}
    timeout-minutes: 15
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
      ENV: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Prepare client container image for deployment
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: artifact prepare:client:${{env.ENV}} ${{ env.IMAGE_TAG }}

  prepare-server:
    name: Prepare server
    needs: changes
    if: needs.changes.outputs.any == 'true'
    runs-on: ${{ vars.BUILD_RUNS_ON || 'gcp-proto-vm' }}
    timeout-minutes: 15
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
      ENV: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
      # Server image is always needed during deployment when running db migrations using server container image
      taito_ci_pull_always: true
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Prepare server container image for deployment
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: artifact prepare:server:${{env.ENV}} ${{ env.IMAGE_TAG }}

  prepare-playwright:
    name: Prepare playwright
    needs: changes
    if: needs.changes.outputs.any == 'true'
    runs-on: ${{ vars.BUILD_RUNS_ON || 'gcp-proto-vm' }}
    timeout-minutes: 15
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
      ENV: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Prepare playwright container image for deployment
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: artifact prepare:playwright:${{env.ENV}} ${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy
    needs: [prepare-client, prepare-server, prepare-storybook]
    runs-on: ${{ vars.DEPLOYMENT_RUNS_ON || 'gcp-proto-vm' }}
    timeout-minutes: 7
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    permissions:
      contents: read
      pull-requests: write
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
      ENV: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Always recreate database for PR environments
        if: ${{ github.event_name == 'pull_request' }}
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: db recreate:${{env.ENV}}

      - name: Deploy database migrations
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: db deploy:${{env.ENV}}
        env:
          taito_image: ghcr.io/taitounited/taito-cli:ci-gcp-dev
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          DOCKER_HOST_PATH: ${{ runner.workspace }}/./${{ github.event.repository.name }}
          COMPOSE_PROJECT_NAME: ${{ runner.name }}

      - name: Deploy the application
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: deployment deploy:${{env.ENV}} ${{env.IMAGE_TAG}} ${{ format('"{0}"', join(github.event.pull_request.labels.*.name, '" "')) }}

      - name: Wait for application to start after deployment
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: deployment wait:${{env.ENV}}

      - name: Add PR environment url on PR as comment
        if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'PR - has env')}}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Your application is now running at https://xx-${{env.ENV}}.proto.taitodev.com

  test-playwright:
    name: Test playwright
    needs: [changes, deploy, prepare-playwright]
    if: needs.changes.outputs.any == 'true'
    runs-on: ${{ vars.TEST_RUNS_ON || 'gcp-proto-vm' }}
    timeout-minutes: 15
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
      ENV: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Run tests
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: test:playwright:${{env.ENV}}
        env:
          taito_image: ghcr.io/taitounited/taito-cli:ci-gcp-dev
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          DOCKER_HOST_PATH: ${{ runner.workspace }}/./${{ github.event.repository.name }}
          COMPOSE_PROJECT_NAME: ${{ runner.name }}
          CI: true

      - name: Upload playwright logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: playwright/test-results

  test-server:
    name: Test server
    needs: [changes, deploy]
    if: needs.changes.outputs.server == 'true'
    runs-on: ${{ vars.TEST_RUNS_ON || 'gcp-proto-vm' }}
    timeout-minutes: 15
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
      ENV: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Run tests
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: test:server:${{env.ENV}}
        env:
          taito_image: ghcr.io/taitounited/taito-cli:ci-gcp-dev
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          DOCKER_HOST_PATH: ${{ runner.workspace }}/./${{ github.event.repository.name }}
          COMPOSE_PROJECT_NAME: ${{ runner.name }}
          CI: true

  stop:
    name: Stop
    if: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'PR - has env') }}
    needs: [test-playwright, test-server]
    runs-on: ${{ vars.DEPLOYMENT_RUNS_ON || 'gcp-proto-vm' }}
    timeout-minutes: 7
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
      ENV: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Stop the PR environment
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: stop:${{env.ENV}}

  release:
    name: Release
    if: ${{ github.event_name != 'pull_request' }}
    needs: [test-playwright, test-server]
    runs-on: ${{ vars.BUILD_RUNS_ON || 'gcp-proto-vm' }}
    timeout-minutes: 7
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
      ENV: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Release client image artifact
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: artifact release:client:${{env.ENV}} ${{ env.IMAGE_TAG }}

      - name: Release server image artifact
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: artifact release:server:${{env.ENV}} ${{ env.IMAGE_TAG }}

      - name: Release build
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: build release:${{env.ENV}}

      # TODO: enable once you get docker based git operations working on CI/CD
      # - name: Make a git tag for release
      #   uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
      #   with:
      #     args: tag ${{env.ENV}}-${{ env.IMAGE_TAG }}
      #   if: ${{ github.event_name != 'pull_request' }}

  # NOTE: You can use this to release changes automatically to the next application
  # environment. However, releasing every single PR automatically all the way to
  # production is discouraged to avoid any unnecessary disruption or performance
  # degradation (e.g. because of cache invalidation). You should bundle multiple
  # changes into one production release instead.
  auto-merge:
    name: Auto-merge
    # NOTE: Define source branches automatically to be merged here, for example: fromJson('["dev", "test"]')
    if: contains(fromJson('[]'), github.ref_name) && github.event_name != 'pull_request'
    needs: [release]
    runs-on: ${{ vars.BUILD_RUNS_ON || 'gcp-proto-vm' }}
    timeout-minutes: 3
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    env:
      ENV: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge to the next application environment
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: env merge:${{env.ENV}}

  # TODO: notify
  # notify:
  # - name: Notify slack fail
  #   if: failure()
  #   timeout-minutes: 2
  #   uses: voxmedia/github-action-slack-notify-build@v1
  #   with:
  #     channel_id: builds # TODO: project channel name
  #     status: FAILED
  #     color: danger
  #   env:
  #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
