name: Stop the PR environment on pull-request close
on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  stop:
    name: Stop
    runs-on: ${{ vars.DEPLOYMENT_RUNS_ON || 'TODO_DEFAULT_RUNNER' }}
    timeout-minutes: 10
    environment: ${{ github.event_name == 'pull_request' && 'pr' || github.ref_name }}
    if: ${{ ! endsWith(github.head_ref, '-no-env') }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
      ENV: ${{ format('pr-{0}', github.event.pull_request.number) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      # NOTE: It would be better to execute this on the pipeline that deploys to dev, but I guess
      # it cannot access the pull-request labels
      - name: Recreate target (dev) database if requested
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: db recreate:${{ github.base_ref }}
        if: ${{ github.base_ref == 'dev' && contains(github.event.pull_request.labels.*.name, 'PR - db recreate') }}

      - name: Stop the PR environment
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: stop:${{env.ENV}}

      - name: Drop the database
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: db drop:${{env.ENV}}
