name: Stop the PR environment on pull-request close
on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  init:
    name: Initialize
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref }}
    steps:
      - run: echo "Exposing vars"
    outputs:
      env: ${{ format('pr-{0}', github.event.pull_request.number) }}
      deployment-runs-on: ${{ vars.DEPLOYMENT_RUNS_ON || 'gcp-proto-vm' }}

  stop:
    name: Stop
    needs: [init]
    runs-on: ${{ needs.init.outputs.deployment-runs-on }}
    timeout-minutes: 10
    environment: ${{ github.base_ref }}
    if: ${{ ! endsWith(github.head_ref, '-no-env') }}
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./tmp/GOOGLE_APPLICATION_CREDENTIALS
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO: Remove this hack
      - name: Set Google credentials
        run: |
          mkdir -p ./tmp
          printf "%s" '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_SECRET }}' > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Stop the PR environment
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: stop:${{ needs.init.outputs.env }}

      - name: Drop the database
        uses: docker://ghcr.io/taitounited/taito-cli:ci-gcp-dev
        with:
          args: db drop:${{ needs.init.outputs.env }}
